import { expect, test } from "@playwright/test";

test("initialize, reproduce, inspect protocol text, and annotate", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("article img").first()).toBeVisible();
  await expect(page.getByText("Gaia", { exact: true }).first()).toBeVisible();
  await expect(page.getByText("Eros", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "创世", exact: true }).click();
  const rootName = `Root-${Date.now()}`;
  await page.getByLabel("创世节点名称").fill(rootName);
  await page.getByRole("button", { name: "创建创世节点", exact: true }).click();
  await expect(page.getByText(rootName).first()).toBeVisible({ timeout: 20_000 });
  const rootDetail = await page.request.get("/api/graph").then((response) => response.json());
  expect(rootDetail.nodes.find((node: { name: string }) => node.name === rootName).generation).toBe(0);
  expect(rootDetail.nodes.find((node: { name: string }) => node.name === rootName).type).toBe("GENESIS");
  await page.getByLabel("关闭").click();
  await page.getByRole("button", { name: "繁衍", exact: true }).click();
  const graph = await page.request.get("/api/graph").then((response) => response.json());
  await page.getByLabel("节点 A").selectOption(graph.nodes.find((node: { name: string }) => node.name === "Gaia").id);
  await page.getByLabel("节点 B").selectOption(graph.nodes.find((node: { name: string }) => node.name === "Psyche").id);
  const name = `Astra-${Date.now()}`;
  await page.getByLabel("新节点名称").fill(name);
  await expect(page.getByTestId("similarity-preview")).toBeVisible();
  await page.getByRole("button", { name: "创建不可变节点" }).click();
  await expect(page.getByText(name).first()).toBeVisible({ timeout: 20_000 });
  await page.getByText(name).first().click();
  await expect(page.getByTestId("node-detail").getByAltText(`${name} 的视觉解释`)).toBeVisible();
  await expect(page.getByTestId("full-hash")).toHaveText(/^[0-9a-f]{128}$/);
  const genome = await page.getByTestId("full-hash").textContent();
  await expect(page.getByTestId("flipped-positions")).not.toBeEmpty();
  await expect(page.getByText("实体设定 · 4 组双 Token")).toBeVisible();
  await expect(page.getByText("内在特征 · 去重视图")).toBeVisible();
  await expect(page.getByTestId("entity-prompt")).not.toBeVisible();
  await expect(page.locator('[data-token-role="primary"]')).toHaveCount(1);
  await expect(page.locator('[data-token-role="auxiliary"]')).toHaveCount(3);
  await expect(page.getByText("锚点附带特征 · Anchor traits", { exact: true })).toHaveCount(4);
  await page.getByText("Token 派生的确定性 Prompt", { exact: true }).click();
  await expect(page.getByTestId("entity-prompt")).toContainText("Generate one coherent visual interpretation of a single entity.");
  await page.getByLabel("记述").fill("A public note <b>kept as plain text</b>");
  await page.getByRole("button", { name: "追加记述" }).click();
  await expect(page.getByText(/记述已追加/)).toBeVisible();
  await expect(page.getByTestId("full-hash")).toHaveText(genome ?? "");
  await page.getByRole("button", { name: "生成新解释" }).click();
  await expect(page.getByText(/新的视觉解释已生成/)).toBeVisible();
  await expect(page.getByAltText("视觉解释", { exact: true })).toHaveCount(2);
  await expect(page.getByTestId("full-hash")).toHaveText(genome ?? "");
});
